spring.application.name=RailwayCrossingManagement
spring.datasource.url=jdbc:mysql://localhost:3306/railway
spring.datasource.username=root
spring.datasource.password=4503
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


